import { useState } from 'react'
import { FileDown, ChevronRight, Clock, BookOpen, RotateCcw, ChevronDown, Sparkles, Plus } from 'lucide-react'
import { Summary } from '@/utils/summary'


interface ResultScreenProps {
    summaries: Summary[]
    onSelectTopic: (topic: Summary) => void
    onSelectRedo: () => void
}

export function ResultScreen({ summaries, onSelectTopic, onSelectRedo }: ResultScreenProps) {
    const [showRedoMenu, setShowRedoMenu] = useState(false)

    return (
        <div className="flex-1 flex flex-col space-y-6 animate-in fade-in slide-in-from-right-4 duration-500 overflow-hidden">
            <header className="flex items-center justify-between shrink-0">
                <div className="flex flex-col">
                    <h2 className="text-xl font-bold tracking-tight">Lecture Insights</h2>
                    <p className="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Generated by AI Agent</p>
                </div>
                <div className="flex gap-2">
                    {/* Redo Split Button */}
                    <div className="relative flex items-center">
                        <button
                            className="flex items-center gap-2 px-3 py-1.5 bg-secondary text-secondary-foreground rounded-l-lg text-xs font-semibold hover:bg-secondary/80 transition-colors border-r border-background/20"
                            onClick={() => onSelectRedo()}
                        >
                            <RotateCcw className="w-3.5 h-3.5" />
                            Redo
                        </button>
                        <button
                            className="px-1.5 py-1.5 bg-secondary text-secondary-foreground rounded-r-lg hover:bg-secondary/80 transition-colors"
                            onClick={() => setShowRedoMenu(!showRedoMenu)}
                        >
                            <ChevronDown className="w-4 h-4" />
                        </button>

                        {showRedoMenu && (
                            <div className="absolute top-full right-0 mt-2 w-48 bg-card border border-border rounded-xl shadow-xl z-50 animate-in fade-in zoom-in-95 duration-200">
                                <button
                                    className="w-full flex items-center gap-3 px-4 py-3 text-xs font-medium hover:bg-accent transition-colors text-left rounded-xl"
                                    onClick={() => {
                                        console.log('Add prompt to AI')
                                        setShowRedoMenu(false)
                                    }}
                                >
                                    <Plus className="w-4 h-4 text-primary" />
                                    Add prompt to AI
                                </button>
                            </div>
                        )}
                    </div>

                    <button
                        className="flex items-center gap-2 px-3 py-1.5 bg-primary text-primary-foreground rounded-lg text-xs font-semibold hover:bg-primary/90 transition-colors shadow-sm"
                        title="Export PDF"
                    >
                        <FileDown className="w-3.5 h-3.5" />
                        PDF
                    </button>
                </div>
            </header>

            <div className="flex-1 overflow-hidden flex flex-col min-h-0 bg-accent/10 rounded-3xl border border-border/50">
                <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                    <div className="grid gap-4">
                        {summaries.map((summary) => (
                            <div
                                key={summary.id}
                                onClick={() => onSelectTopic(summary)}
                                className="group relative bg-card hover:bg-accent/30 border border-border p-5 rounded-2xl cursor-pointer transition-all duration-300 hover:shadow-lg active:scale-[0.98]"
                            >
                                <div className="flex items-start justify-between mb-3">
                                    <div className="flex items-center gap-2 px-2.5 py-1 bg-primary/10 text-primary rounded-full">
                                        <Clock className="w-3 h-3" />
                                        <span className="text-[10px] font-bold font-mono uppercase tracking-wider">{summary.timestamp}</span>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <button
                                            className="p-1.5 hover:bg-primary/10 rounded-lg text-muted-foreground hover:text-primary transition-colors"
                                            onClick={(e) => {
                                                e.stopPropagation()
                                                console.log('AI Explanation for', summary.title)
                                            }}
                                            title="AI Explanation"
                                        >
                                            <Sparkles className="w-4 h-4" />
                                        </button>
                                        <ChevronRight className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors" />
                                    </div>
                                </div>

                                <div className="space-y-2">
                                    <h3 className="font-bold text-base leading-tight group-hover:text-primary transition-colors">
                                        {summary.title}
                                    </h3>
                                    <p className="text-sm text-muted-foreground line-clamp-2 leading-relaxed">
                                        {summary.summary}
                                    </p>
                                </div>

                                <div className="mt-4 flex items-center gap-4 border-t border-border/50 pt-4">
                                    <div className="flex items-center gap-1.5">
                                        <BookOpen className="w-3.5 h-3.5 text-muted-foreground" />
                                        <span className="text-[11px] font-medium text-muted-foreground uppercase">{summary.details.length} Sub-topics</span>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}